# Generated by Django 4.2.26 on 2025-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_prescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diploma_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Diploma No'),
        ),
    ]
