# Generated by Django 4.2.26 on 2025-12-12 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_psychologist',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_psychologist': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL, verbose_name='Atanmış Psikolog'),
        ),
    ]
