# Generated by Django 4.2.26 on 2026-01-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_assigned_psychologist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='diploma_no',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Hakkında / Notlar'),
        ),
        migrations.AddField(
            model_name='user',
            name='psychologist_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Psikolog Notları (Özel)'),
        ),
    ]
