# Generated by Django 4.2.26 on 2026-01-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_individual',
            field=models.BooleanField(default=False, verbose_name='Bireysel Kullanıcı Mı?'),
        ),
    ]
