# Generated by Django 4.2.26 on 2026-02-24 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_birth_date_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'is_individual': False, 'is_psychologist': False, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
