# Generated by Django 4.2.26 on 2026-02-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('icon', models.CharField(choices=[('fa-music', 'Müzik Notası'), ('fa-cloud-rain', 'Yağmur'), ('fa-tree', 'Orman'), ('fa-water', 'Su / Okyanus'), ('fa-om', 'Zen'), ('fa-spa', 'Spa'), ('fa-wind', 'Rüzgar'), ('fa-fire', 'Ateş'), ('fa-leaf', 'Yaprak'), ('fa-moon', 'Ay'), ('fa-sun', 'Güneş'), ('fa-snowflake', 'Kar'), ('fa-dove', 'Barış'), ('fa-guitar', 'Gitar'), ('fa-drum', 'Davul')], default='fa-music', max_length=50, verbose_name='İkon')),
                ('color', models.CharField(choices=[('from-violet-400 to-purple-600', 'Mor'), ('from-blue-400 to-blue-600', 'Mavi'), ('from-emerald-400 to-emerald-600', 'Yeşil'), ('from-cyan-400 to-blue-500', 'Camgöbeği'), ('from-amber-400 to-orange-500', 'Turuncu'), ('from-rose-400 to-pink-600', 'Pembe'), ('from-indigo-400 to-blue-600', 'İndigo'), ('from-teal-400 to-cyan-600', 'Teal'), ('from-stone-400 to-stone-600', 'Gri')], default='from-violet-400 to-purple-600', max_length=80, verbose_name='Renk')),
                ('audio_file', models.FileField(upload_to='music/', verbose_name='Ses Dosyası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Müzik Parçası',
                'verbose_name_plural': 'Müzik Parçaları',
                'ordering': ['order', 'title'],
            },
        ),
    ]
