# Generated by Django 4.2.26 on 2026-03-25 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_add_musictrack'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doğrulama Kodu Süresi Dolacak'),
        ),
        migrations.AlterField(
            model_name='listeninglog',
            name='frequency',
            field=models.CharField(choices=[('delta', 'Delta (0.5-4 Hz) - Deep Sleep'), ('theta', 'Theta (4-8 Hz) - Meditation'), ('alpha', 'Alpha (8-12 Hz) - Relaxation'), ('beta', 'Beta (12-30 Hz) - Focus'), ('gamma', 'Gamma (30-100 Hz) - Peak Performance')], max_length=20, null=True, verbose_name='Dinlenen Frekans'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='color',
            field=models.CharField(choices=[('violet', 'Mor'), ('blue', 'Mavi'), ('emerald', 'Yeşil'), ('cyan', 'Camgöbeği'), ('amber', 'Turuncu'), ('rose', 'Pembe'), ('indigo', 'İndigo'), ('teal', 'Teal'), ('stone', 'Gri')], default='violet', max_length=20, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(choices=[('delta', 'Delta (0.5-4 Hz) - Deep Sleep'), ('theta', 'Theta (4-8 Hz) - Meditation'), ('alpha', 'Alpha (8-12 Hz) - Relaxation'), ('beta', 'Beta (12-30 Hz) - Focus'), ('gamma', 'Gamma (30-100 Hz) - Peak Performance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersubscription_set', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
