# Generated by Django 4.2.30 on 2026-06-02 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_listeninglog_unique_per_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_quality', models.IntegerField(verbose_name='Uyku Kalitesi')),
                ('stress_level', models.IntegerField(verbose_name='Stres Seviyesi')),
                ('focus_level', models.IntegerField(verbose_name='Odak / Konsantrasyon')),
                ('mood_score', models.IntegerField(verbose_name='Ruh Hali')),
                ('anxiety_level', models.IntegerField(verbose_name='Anksiyete Seviyesi')),
                ('fatigue_level', models.IntegerField(verbose_name='Yorgunluk Seviyesi')),
                ('recommended_frequency', models.CharField(choices=[('delta', 'Delta (0.5-4 Hz) - Deep Sleep'), ('theta', 'Theta (4-8 Hz) - Meditation'), ('alpha', 'Alpha (8-12 Hz) - Relaxation'), ('beta', 'Beta (12-30 Hz) - Focus'), ('gamma', 'Gamma (30-100 Hz) - Peak Performance')], max_length=20, verbose_name='Önerilen Frekans')),
                ('recommended_minutes', models.IntegerField(verbose_name='Önerilen Günlük Süre (dk)')),
                ('ml_confidence', models.FloatField(default=0.0, verbose_name='Model Güven Skoru')),
                ('plan_start_date', models.DateField(verbose_name='Plan Başlangıç Tarihi')),
                ('plan_expires_at', models.DateField(verbose_name='Plan Bitiş Tarihi')),
                ('renewal_notified', models.BooleanField(default=False, verbose_name='Yenileme Bildirimi Gönderildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'is_individual': True}, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Anket Yanıtı',
                'verbose_name_plural': 'Anket Yanıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='main_survey_user_id_ab4afc_idx')],
            },
        ),
    ]
