# Generated by Django 4.2.30 on 2026-06-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_add_survey_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='recommended_days',
            field=models.IntegerField(default=15, verbose_name='Önerilen Program Süresi (gün)'),
        ),
    ]
